config/routes.rb
Rails.application.routes.draw do

  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'

  resource :charges, only: [:new, :create] do
    member do
      get 'to_standard'
    end
  end

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis
  has_many :collaborators
  has_many :collaborated_wikis, through: :collaborators, source: :wiki

  enum role: [:standard, :premium, :admin]

  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :standard
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

def user_not_authorized
  flash[:warning] = "You are not authrozed to perfom this action."
  redirect_to(request.referrer || root_path)
end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens - per Bloc explanation...
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app-stored
      amount: 1500,
      description: "Blocipedia Premium Account Access - #{current_user.email}",
      currency: 'usd'
    )

    current_user.premium!

    flash[:notice] = "Thank You for your patronage, #{current_user.email}. We appreciate the support!"
    redirect_to root_path

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.

    rescue Stripe::CardError => e
      flash[:alert] = e.messages
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Account Access - #{current_user.email}",
      amount: 1500
    }
  end

  def to_standard
    current_user.standard!
    flash[:notice] = "We are sorry to see you cancel Premium Membership, #{current_user.email}."
    redirect_to root_path
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator was added to this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not added. Please try again."
      render :show
    end
  end

  def destroy
    # @wiki.users.delete(user)
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed from this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not removed. Please try again."
      render :show
    end
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#before_action :authenticate_user!, except: [:index, :about]

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  after_action :verify_authorized, :except => :index

  include Pundit
  protect_from_forgery

  def index
    @wikis = policy_scope(Wiki).page(params[:page]).per(10).order(:updated_at)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user
    @wiki.private = params[:wiki][:private]

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    @collaborator = Collaborator.new
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "The Wiki, \"#{@wiki.title}\" was deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting this wiki. Please try again."
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = {
      filter_html:  true,
      hard_wrap:    true,
      link_attributes: { rel: 'nofollow', taget: "_blank" },
      fenced_code_blocks: true
    }

    extensions = {
      autolink:     true,
      superscript:  true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
		<div class="form-group">
      <h3>List of Users available to add as Collaborators</h3>
			<% @users.each do |user| %>
				<h4><%= user.email %> </h4>
				<% if @wiki.users.include? user %>
					<%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
				<% else %>
					<%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-info' %>
				<% end %>
			<% end %>
		</div>
<% end %>

app/views/collaborators/_users.html.erb
<h4>Collaborators</h4>
<ul>
	<% @wiki.collaborators.each do |collaborator| %>
		<li>
			<h4><%= collaborator.user.email %> <%= link_to "", "/wikis/#{@wiki.id}/collaborators/#{collaborator.id}", method: :delete, class: 'glyphicon glyphicon-remove' %> </h4>
		</li>
	<% end %>
</ul>

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>

<%= form_for [@wiki] do |f| %>

  <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <%= collection_check_boxes(:wiki, :user_ids, User.all - [f.object.user], :id, :email) do |u| %>
    <div class="checkbox">
      <%= u.label do %>
        <%= u.check_box %>
        <%= u.object.email %>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="row app-header">
        <ul class="nav nav-tabs text-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>

          <div class="pull-right user-info">
            <% if user_signed_in? %>
              Signed in as: <strong><%= current_user.email %></strong> |
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </div>
        </ul>
    </div>
    <div class="container">

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div>
<h1>Welcome to the Blocipedia About page!</h1>

<p>While an About page is supposed to contain colorful background for a product/company/person really this is a placeholder.</p>

<p>Currently Blocipedia is just a project from <a href="https://www.bloc.io" target="blank">Bloc.io</a>. It is a Wiki built to demonstrate several objectives listed below.</p>

<p>Objectives listed below are straight from Bloc so I don't want to be accused of plagiarism</p>
<ul>
	<li>Create a basic user scheme for a Ruby on Rails application.</li>
	<li>Give the users of a Ruby on Rails application the ability to sign up for your application using the Devise gem.</li>
	<li>Understand how to create CRUD routes and resources in a Rails Application.</li>
	<li>Explain the difference between authentication and authorization.</li>
	<li>Integrate Stripe third party API callouts.</li>
	<li>Integrate Redcarpet Markdown rendering gem.</li>
</ul>

</div>

app/views/welcome/index.html.erb
<div class="row">

  <div class="text-center welcome-header">
    <p>Blocipedia: Social, Markdown Wikis</p>
  </div>


</div>

<div class="row text-center">
  <div class="welcome-center center-block">
    <h3>Create and share Markdown Wikis</h3>
    <div>
      <% if user_signed_in? %>
        <p>Signed in as: <strong><%= current_user.email %></strong></p>
        <%= link_to "All Wikis", wikis_path, :class => 'btn btn-info' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-primary'  %> or
        <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-primary'  %>
      <% end %>
    </div>
  </div>
</div>

<div class="row text-center welcome-footer">
  <div class="col-md-5 well">
    <h3>Create as many Public Wikis as you want!</h3>
    <p>Free Plan for everyone! Just Sign up!</p>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-5 well">
    <h3>Create Private Wikis!</h3>
    <% if current_user && current_user.premium? %>
      <h4>Welcome Premium Member!</h4>
    <% elsif current_user && current_user.standard? %>
      <p>Click here to upgrade to our Premium Plan Option!</p>
      <%= link_to "Premium Membership", new_charges_path, :class => 'btn btn-primary' %>
    <% else %>
      <p>Premium Plan Option for registered users!</p>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit this Wiki</h1>

<div class="col-md-6">
  <%= form_for @wiki do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter the New Wiki Title" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter your Updated Wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private %>
      <%= f.check_box :private %>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
    <%= link_to "Cancel", @wiki, class: 'btn btn-danger' %>
  </div>
</div>

<div class="col-md-6">
  <p>Wiki uses standard <a href="https://help.github.com/articles/basic-writing-and-formatting-syntax/">GitHub Markdown</a></p>
  <p>Some examples below</p>
  <h3>Headings</h3>
  <ul>
    <li># The largest heading</li>
    <li>## The second largest heading</li>
    <li>###### The smallest heading</li>
  </ul>
  <h3>Styling</h3>
  <ul>
    <li>Bold uses **Bold** or __Bold__</li>
    <li>Italic *Italic* or _Italic_</li>
    <li>Strikethrough ~~Strikethrough~~</li>
  </ul>
  <p>Plus much more....</p>
</div>

<div class="col-md-12">
  <% if @wiki.private %>
    <%= render partial: 'collaborators/form', locals: { f: f } %>
  <% end %>
</div>


<% end %>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2 class="text-center">My Wikis</h2>
  </div>
  <div class="col-md-4">
    <%= link_to "New", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">

        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>

        <div class="text-right">
        <% if wiki.private? %>
          <small>This Private Wiki belongs to <%= wiki.user.email %> created on <%= wiki.created_at %>.</small>
        <% else %>
          <small>Created by <%= wiki.user.email %> on <%= wiki.created_at %>.</small>
        <% end %>
      </div>
        <hr>

      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="text-center">
<h2><%= paginate @wikis %></h2>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="col-md-6">
  <%= form_for @wiki do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter the Wiki Title" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter your Wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private %>
      <%= f.check_box :private %>
    </div>
  <% end %>

  <% if @wiki.private %>
    <%= render partial: 'collaborators/form', locals: { f: f } %>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
    <%= link_to "Cancel", @wiki, class: 'btn btn-danger' %>
  </div>
</div>
<div class="col-md-6">
  <p>Wiki uses standard <a href="https://help.github.com/articles/basic-writing-and-formatting-syntax/">GitHub Markdown</a></p>
  <p>Some examples below</p>
  <h3>Headings</h3>
  <ul>
    <li># The largest heading</li>
    <li>## The second largest heading</li>
    <li>###### The smallest heading</li>
  </ul>
  <h3>Styling</h3>
  <ul>
    <li>Bold uses **Bold** or __Bold__</li>
    <li>Italic *Italic* or _Italic_</li>
    <li>Strikethrough ~~Strikethrough~~</li>
  </ul>
  <p>Plus much more....</p>
</div>
<% end %>

app/views/wikis/show.html.erb
<div class="col-md-8">
  <h1><%= @wiki.title %></h1>
  <p>Created by <%= @wiki.user.email %></p>

  <div>
    <p><%= markdown(@wiki.body) %></p>
  </div>
</div>

<div class="col-md-4">
  <%= link_to "Back to Wikis", wikis_path, class: 'btn btn-info' %>
  <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>

  <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
  <% end %>

  <% if @wiki.private %>
    <% if Collaborator.exists?(wiki_id: @wiki) %>
      <%= render partial: 'collaborators/users' %>
    <% end %>
  <% end %>


</div>